"""add patients table and foreign key

Revision ID: 58faf8bfd11a
Revises: 039fd17b2784
Create Date: 2026-03-05 15:24:33.455904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58faf8bfd11a'
down_revision: Union[str, Sequence[str], None] = '039fd17b2784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    # 既存データ対応: デモ患者を挿入（records テーブルに patient_id=1 のデータがある場合）
    op.execute("INSERT INTO patients (id, name) VALUES (1, 'デモ患者') ON CONFLICT (id) DO NOTHING")
    op.create_foreign_key('fk_records_patient_id', 'records', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_records_patient_id', 'records', type_='foreignkey')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
